### ISSUE TITLE
Include data.data_loader

### ISSUE THREAD

**Issue by pjl54** [xtarx/StainGAN#2]
Can you upload CreateDataLoader in data.data_loader? I am trying to replicate the paper's results before running my own experiments.

**Comment by AdiaLoveTrance** [comment]
I have the same question. Have you found the solution of the problem? @pjl54 @xtarx

**Comment by pjl54** [comment]
I haven't found a solution. I tried emailing the creator directly using the contact email address in the readme. I will let you know if I get a response.

**Comment by AdiaLoveTrance** [comment]
Thanks! I have emailed the author too! But I haven’t get any response. Keep waiting.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: pjl54 <notifications@github.com>
发送时间: Friday, December 7, 2018 10:12:35 PM
收件人: xtarx/StainGAN
抄送: AdiaLoveTrance; Comment
主题: Re: [xtarx/StainGAN] Include data.data_loader (#2)


I haven't found a solution. I tried emailing the creator directly using the contact email address in the readme. I will let you know if I get a response.

―

**Comment by xtarx** [comment]
Hello @pjl54 and @AdiaLoveTrance sorry for late response,  it's uploaded now ( https://github.com/xtarx/StainGAN/commit/0871a6b7329d4901c2ae3706e2c699de8ee11568)
